/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZeroImprovvisazioneMasterclassRouteImport } from './routes/zero-improvvisazione-masterclass'
import { Route as ScaricaCalendarioLancioRouteImport } from './routes/scarica-calendario-lancio'
import { Route as GrazieConsulenzaStrategicaRouteImport } from './routes/grazie-consulenza-strategica'
import { Route as EasyMailPackRouteImport } from './routes/easy-mail-pack'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ConsulenzaStrategicaRouteImport } from './routes/consulenza-strategica'
import { Route as IndexRouteImport } from './routes/index'

const ZeroImprovvisazioneMasterclassRoute =
  ZeroImprovvisazioneMasterclassRouteImport.update({
    id: '/zero-improvvisazione-masterclass',
    path: '/zero-improvvisazione-masterclass',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScaricaCalendarioLancioRoute = ScaricaCalendarioLancioRouteImport.update({
  id: '/scarica-calendario-lancio',
  path: '/scarica-calendario-lancio',
  getParentRoute: () => rootRouteImport,
} as any)
const GrazieConsulenzaStrategicaRoute =
  GrazieConsulenzaStrategicaRouteImport.update({
    id: '/grazie-consulenza-strategica',
    path: '/grazie-consulenza-strategica',
    getParentRoute: () => rootRouteImport,
  } as any)
const EasyMailPackRoute = EasyMailPackRouteImport.update({
  id: '/easy-mail-pack',
  path: '/easy-mail-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsulenzaStrategicaRoute = ConsulenzaStrategicaRouteImport.update({
  id: '/consulenza-strategica',
  path: '/consulenza-strategica',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consulenza-strategica': typeof ConsulenzaStrategicaRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/easy-mail-pack': typeof EasyMailPackRoute
  '/grazie-consulenza-strategica': typeof GrazieConsulenzaStrategicaRoute
  '/scarica-calendario-lancio': typeof ScaricaCalendarioLancioRoute
  '/zero-improvvisazione-masterclass': typeof ZeroImprovvisazioneMasterclassRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consulenza-strategica': typeof ConsulenzaStrategicaRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/easy-mail-pack': typeof EasyMailPackRoute
  '/grazie-consulenza-strategica': typeof GrazieConsulenzaStrategicaRoute
  '/scarica-calendario-lancio': typeof ScaricaCalendarioLancioRoute
  '/zero-improvvisazione-masterclass': typeof ZeroImprovvisazioneMasterclassRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consulenza-strategica': typeof ConsulenzaStrategicaRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/easy-mail-pack': typeof EasyMailPackRoute
  '/grazie-consulenza-strategica': typeof GrazieConsulenzaStrategicaRoute
  '/scarica-calendario-lancio': typeof ScaricaCalendarioLancioRoute
  '/zero-improvvisazione-masterclass': typeof ZeroImprovvisazioneMasterclassRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consulenza-strategica'
    | '/cookie-policy'
    | '/easy-mail-pack'
    | '/grazie-consulenza-strategica'
    | '/scarica-calendario-lancio'
    | '/zero-improvvisazione-masterclass'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consulenza-strategica'
    | '/cookie-policy'
    | '/easy-mail-pack'
    | '/grazie-consulenza-strategica'
    | '/scarica-calendario-lancio'
    | '/zero-improvvisazione-masterclass'
  id:
    | '__root__'
    | '/'
    | '/consulenza-strategica'
    | '/cookie-policy'
    | '/easy-mail-pack'
    | '/grazie-consulenza-strategica'
    | '/scarica-calendario-lancio'
    | '/zero-improvvisazione-masterclass'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsulenzaStrategicaRoute: typeof ConsulenzaStrategicaRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  EasyMailPackRoute: typeof EasyMailPackRoute
  GrazieConsulenzaStrategicaRoute: typeof GrazieConsulenzaStrategicaRoute
  ScaricaCalendarioLancioRoute: typeof ScaricaCalendarioLancioRoute
  ZeroImprovvisazioneMasterclassRoute: typeof ZeroImprovvisazioneMasterclassRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zero-improvvisazione-masterclass': {
      id: '/zero-improvvisazione-masterclass'
      path: '/zero-improvvisazione-masterclass'
      fullPath: '/zero-improvvisazione-masterclass'
      preLoaderRoute: typeof ZeroImprovvisazioneMasterclassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scarica-calendario-lancio': {
      id: '/scarica-calendario-lancio'
      path: '/scarica-calendario-lancio'
      fullPath: '/scarica-calendario-lancio'
      preLoaderRoute: typeof ScaricaCalendarioLancioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grazie-consulenza-strategica': {
      id: '/grazie-consulenza-strategica'
      path: '/grazie-consulenza-strategica'
      fullPath: '/grazie-consulenza-strategica'
      preLoaderRoute: typeof GrazieConsulenzaStrategicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/easy-mail-pack': {
      id: '/easy-mail-pack'
      path: '/easy-mail-pack'
      fullPath: '/easy-mail-pack'
      preLoaderRoute: typeof EasyMailPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulenza-strategica': {
      id: '/consulenza-strategica'
      path: '/consulenza-strategica'
      fullPath: '/consulenza-strategica'
      preLoaderRoute: typeof ConsulenzaStrategicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsulenzaStrategicaRoute: ConsulenzaStrategicaRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  EasyMailPackRoute: EasyMailPackRoute,
  GrazieConsulenzaStrategicaRoute: GrazieConsulenzaStrategicaRoute,
  ScaricaCalendarioLancioRoute: ScaricaCalendarioLancioRoute,
  ZeroImprovvisazioneMasterclassRoute: ZeroImprovvisazioneMasterclassRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
