/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScaricaCalendarioLancioRouteImport } from './routes/scarica-calendario-lancio'
import { Route as EasyMailPackRouteImport } from './routes/easy-mail-pack'
import { Route as IndexRouteImport } from './routes/index'

const ScaricaCalendarioLancioRoute = ScaricaCalendarioLancioRouteImport.update({
  id: '/scarica-calendario-lancio',
  path: '/scarica-calendario-lancio',
  getParentRoute: () => rootRouteImport,
} as any)
const EasyMailPackRoute = EasyMailPackRouteImport.update({
  id: '/easy-mail-pack',
  path: '/easy-mail-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/easy-mail-pack': typeof EasyMailPackRoute
  '/scarica-calendario-lancio': typeof ScaricaCalendarioLancioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/easy-mail-pack': typeof EasyMailPackRoute
  '/scarica-calendario-lancio': typeof ScaricaCalendarioLancioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/easy-mail-pack': typeof EasyMailPackRoute
  '/scarica-calendario-lancio': typeof ScaricaCalendarioLancioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/easy-mail-pack' | '/scarica-calendario-lancio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/easy-mail-pack' | '/scarica-calendario-lancio'
  id: '__root__' | '/' | '/easy-mail-pack' | '/scarica-calendario-lancio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EasyMailPackRoute: typeof EasyMailPackRoute
  ScaricaCalendarioLancioRoute: typeof ScaricaCalendarioLancioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scarica-calendario-lancio': {
      id: '/scarica-calendario-lancio'
      path: '/scarica-calendario-lancio'
      fullPath: '/scarica-calendario-lancio'
      preLoaderRoute: typeof ScaricaCalendarioLancioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/easy-mail-pack': {
      id: '/easy-mail-pack'
      path: '/easy-mail-pack'
      fullPath: '/easy-mail-pack'
      preLoaderRoute: typeof EasyMailPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EasyMailPackRoute: EasyMailPackRoute,
  ScaricaCalendarioLancioRoute: ScaricaCalendarioLancioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
